### ISSUE TITLE
Add (POST/PUT) param attribute/relationship whitelisting

### ISSUE THREAD

**Issue by alanpeabody** [AgilionApps/ja_serializer#10]
Something like:

```
JaSerializer.permit_params(conn.params, attributes: [:title, :body], relationships: [:category, :author])
```

**Comment by thewalkingtoast** [comment]
@alanpeabody Shouldn't the serializer only concern itself with decoding the payload into a map and user land code or a framework like Phoenix determine what is permissible in said map?

**Comment by alanpeabody** [comment]
Yes, that is likely true, however I have had a couple of people request "reverse serialization". Maybe it just becomes a plug of sort that unwraps the JSON-API request but lets the framework select the data.

How are you handling this now in Phoenix?

**Comment by ianwalter** [comment]
+1 for more convenient deserialization in general
How about adding a function to `JaSerializer` so that model serializer definitions can be reused to deserialize? It could work like @thewalkingtoast described:
```elixir
def create(conn, %{"data" => data}) do
  author = AuthorSerializer.deserialize data
# ...
```
This can be separate and doesn't preclude the original idea of a plug to whitelist parameters.

**Comment by alanpeabody** [comment]
Better late then never?

The [`JaSerializer.Params.to_attributes/1`](https://hexdocs.pm/ja_serializer/0.9.0/JaSerializer.Params.html#to_attributes/1 ) function provides a helper function for merging attributes, type and relationships. You can then use take on the resulting map to filter.

It isn't the full deserializer or a specific whitelist, but I believe it hits the pain points while remaining flexible.
