### ISSUE TITLE
Optional relations

### ISSUE THREAD

**Issue by chrisjowen** [AgilionApps/ja_serializer#103]
Hey There, 

Am I missing something but I don't see a way of optionally specifying a relationship. The include flag seems to specify whether to simply linking to relationship or to side load it, but I think it seems valid to me  in some cases to also do neither. Currently if I specify i.e. a has_one relationship in the serializer and I have not fetched the relationship then (assuming Ecto) this bombs when trying to render. 

It would be nice to be able to specify the relationship as optional and if the data has not ben fetched then the serializer will simply ignore when rendering.

**Comment by alanpeabody** [comment]
Thanks for the feedback @chrisjowen. There have been a couple of requests oriented around this.

I will continue thinking about how to best support this kind of use case without making thing more complicated.

**Comment by alanpeabody** [comment]
0.10.0 has support for this via the :identifiers option. More sophisticated situations can be handled with the relationships callback.
