### ISSUE TITLE
has_one link construction in views

### ISSUE THREAD

**Issue by rynam0** [AgilionApps/ja_serializer#107]
Hi @alanpeabody,
Is there a suggested pattern for creating links to "belongs_to" resources?  I have had success in including these (include: true) for the most part but now I would like to link to a "belongs_to" resource (as it is a fairly large model with many relationships of its own).  What I'd like to be able to do here is to create a link to this model's existing :show controller route but I haven't quite figured out how to do so as the below doesn't work:

    defmodule MyModule.FooView do
      use MyModule.Web, :view

      location "/api/foos/:id"
      attributes [:name]
      has_one :bar, link: "/api/bars/:bar_id"
    end

I have tried variations of this too but this requires preloading this relationship (just to use the id) and then I get hit with "protocol String.Chars not implemented for %MyModule.Bar":

   
    has_one :bar, link: "/api/bars/:bar.id"

For "has_many"  relationships I find the sub-resource links work pretty well:

    has_many :bars, link: "/api/foos/:id/bars"

Is there a secret (or something completely obvious I've overlooked) to creating the belongs_to links I'm after?  Any ideas or insight would be greatly appreciated.

**Comment by rynam0** [comment]
Ok, so the "completely obvious" part was that I could simply not link the resource and use "include: false". This totally addresses the issue I was facing with not wanting to include the resource but it seems odd to provide links for some relationships but not for others.  WDYT?

**Comment by alanpeabody** [comment]
Hey @rynam0!

It seems like you have the original question figured out?

Your initial `has_one :bar, link: "/api/bars/:bar_id"` as long as the data being serialized (a `%Foo{}`) has a `:bar_id` field. If that isn't working something is most definitely wrong.

In terms of when to link, reference, or include data, that is one of those things that depends on the project and typical use case in my experience.

I would typically link to has_many unless they are usually used/displayed at the same time as the parent. No need to fetch, serialize, and push something over the wire you are not actually using.

I would always include something that is always used, especially if it is unique to the object being serialized. This applies to has_one(/belongs_to) and has_many.

If there is a decent chance the client already has the related object I would just reference it. A good example of that is when you have a list of users in a chat room. I would only send the user id and type (the resource identified object) and let the client relate to the user.

Frankly the JSON-API spec provides a lot of flexibility and JaSerializer tries to accommodate as much as possible, however it has led to an unclear DSL and lacking documentation and understanding. The (well thought out) handling of preloading in Ecto also plays into the complexity factor.

It has long been on my list to make the relationship DSL optional, make the relationship definition and DSL full featured while being simple and easy to understand, and of course, document the crap out of it.

**Comment by rynam0** [comment]
Thanks for the detailed and thoughtful response!  Yes, I think my initial issue has been worked out using `include: false` but I guess I'm still a bit unclear on the differences in behavior between a "reference" and a "link".  Wouldn't both of these strategies amount to a lazy load of the associated model (loaded when used)?  Not completely understanding the difference here is likely the root of my confusion regarding when to use a link vs a type/id reference.

My Foo model does include a "bar_id" field so I'll investigate this further.  Thanks for clarifying that this should be working!

**Comment by alanpeabody** [comment]
A reference should work with a value that is already loaded in your store (eg Ember Data or React), where as a link you always have to retrieve.

**Comment by rynam0** [comment]
Thanks, @alanpeabody.  This makes sense and that is exactly the behavior I see in my app.  I'm still fighting with creating a link for a belongs_to association though.  I've tried a few things:

    schema "foos" do
        belongs_to :bar, MyModule.Bar
    end

    defmodule MyModule.FooView do
        use MyModule.Web, :view

        location "/api/foos/:id"
        has_one :bar, link: "/api/bars/:bar_id"
    end

This results in `undefined function MyModule.FooView.structure_type_enum_id/2`

Thinking about your comment about the `%Foo{}` having a `bar_id` field, I then tried to map this differently but this resulted in the same error as above.

    schema "foos" do
        field :bar_id, :integer
    end

I'll put together a test project or attempt to reproduce this in tests and get back to you.  Thanks for the help!

**Comment by alanpeabody** [comment]
Okay, so I was looking/playing with this a bit more. This is a terrible experience, but hopefully it should work for you:

```elixir
  has_one :bar, link: "/api/bars/:bar_id", field: :bar_id, type: "bar"
```

I will start an issue soon with some of the problems with the relationships DSL and some possible solutions.

**Comment by alanpeabody** [comment]
@rynam0 I have updated the docs in master to better explain how the DSL works. Closing this for now, but as always feel free to ping me if you run into any more issues.
