### ISSUE TITLE
[WIP] RFC: Relationship Definition

### ISSUE THREAD

**Issue by alanpeabody** [AgilionApps/ja_serializer#110]
## Problem

The existing relationship DSL leaves something to be desired. In particular there are a handful of problems.

1. The relationships can't be customized quite enough for some uses cases. This leads to people using multiple serializers when they otherwise would only use one. See #103 and #45 as example requests.
2. The DSL is confusing and it's behavior is complicated. Some of this complexity stems from the various  ways JSON-API permits relationships to be represented and returned. Some of it is incidental complexity/confusion added while trying to improve other aspects of the DSL. #107, #71, #47 are examples of some of the issues being seen.
3. The link support could be better then atoms. In particular better support for Phoenix views would be good.

## Proposal

Relationships needs to be simplified while retaining full flexibility. I believe this can be accomplished in two parts.

1. Add an underlying behaviour callback for "relationships" that can be implemented. This function should accept the model and conn while returning a map of relationship structs. The default function will be populated by the DSL if it is used.
2) Create an easy to understand, explicit, well documented relationship definition that can be generated by DSL or in the struct directly.

## Scenarios

The final solution must handle all of:

* Linked relationships 
  * Using phoenix router helpers
  * Using simple strings
  * Both self and related links
* Resource Identifiers
* Resource Identifiers with included data
* Selective includes via the `include` parameter 
* Dynamic types
  * default to relationship name
  * leverage related serializer if provided
  * determine type based on object being serialized

#### Links

*Simple String*

While this is the default support linking mechanism in JaSerializer < 1.0, is it something that should continue to be supported? The "magic" of symbols calling functions as it works now is less then ideal.

```elixir
# DSL
has_one :post, link: "/v1/posts/:post_id" # not apparent how post_id is populated.

# Behaviour
def relationships(model, conn) do 
  %{
    post: %HasOne{related: "/v1/posts/:post_id"}
  }
end

# Relationship Struct
%JaSerializer.Relationship.HasOne{
  id: nil,
  type: nil,
  data: nil,
  related: "/v1/posts/:post_id",
  self: nil
}
```

*Anonymous function (Phoenix helpers)*
```elixir
# DSL
has_many :comments, link: &post_comment_url(&2, &1.id)

# Behaviour
def relationships(model, conn) do 
  %{
    comments: %HasMany{related: &post_comment_url(&2, &1.id)}
  }
end

# Relationship Struct
%JaSerializer.Relationship.HasMany{
  each_id: :id,
  each_type: nil,
  data: nil,
  self: nil,
  related: &post_comment_url(&2, &1.id)
}
```

*Self & Related*

```elixir
# DSL
has_many :comments, 
  related: &post_comment_url(&2, &1.id), 
  self: &post_comment_relationship_url(&2, &1.id)

# Behaviour
def relationships(model, conn) do 
  %{
    comments: %HasMany{
      related: &post_comment_url(&2, &1.id),
      self: &post_comment_relationship_url(&2, &1.id)
    }
  }
end

# Relationship Struct
%JaSerializer.Relationship.HasMany{
  id: nil,
  type: nil,
  data: nil,
  related: &post_comment_url(&2, &1.id),
  self: &post_comment_relationship_url(&2, &1.id)
}
```

#### Resource Identifier

```elixir
# DSL
has_one :category, id: :category_id, type: "category" 
has_many :comments, data: :comments, each_type: "comment"

# Notes
# default type to relationship name if no serializer given.
# default type to relationship if name is given
# id, each_id, and each_type are assumed to be fields if given an atom.
# 

# Behaviour
def relationships(post, conn) do 
  %{
    category: %HasOne{id: post.category_id, type: "category"},
    comments: %HasMany{data: post.comments, each_type: "comment")
  }
end

%JaSerializer.Relationship.HasOne{
  id: 1,
  type: "category",
  data: nil,
  
}
```

Dynamic type:

```elixir
belongs_to :post, id: fn(comment, _conn) -> comment.post_id, type: &(&1.post.type)

%JaSerializer.Relationship.BelongsTo{
  name: :post,
  id: fn(comment, _conn) -> comment.post_id,
  type: &(&1.post.type),
  data: nil
}
```

**Comment by benfalk** [comment]
I **really** like the idea of representing relationships with structures.  One item I think that will prove problematic is that shipping anonymous functions from the DSL from compile time into a runtime structure is very difficult:

```
Macro.escape(fn -> :hello end)
** (ArgumentError) cannot escape #Function<20.50752066/0 in :erl_eval.expr/5>. The supported values are: lists, tuples, maps, atoms, numbers, bitstrings, pids and remote functions in the format &Mod.fun/arity
    (elixir) src/elixir_quote.erl:119: :elixir_quote.argument_error/1
    (elixir) src/elixir_quote.erl:141: :elixir_quote.escape/2
    (elixir) lib/macro.ex:312: Macro.escape/2
```

One item I would like to add to the above list is the links.  I would like to see them get the same kind of love as the relationships and have a structure that also represents them. Expanding on the example you provided from above:

``` elixir
# Relationship Struct
%JaSerializer.Relationship.HasMany{
  id: nil,
  type: nil,
  data: nil,
  links: %{
    related: %JaSerializer.Relationship.Link{meta: &Mod.arity/2, link: &Mod.arity/2, template: nil},
    self: %JaSerializer.Relationship.Link{meta: &Mod.arity/2, link: &Mod.arity/2, template: nil}
  }
}
```

**Comment by benfalk** [comment]
An idea that came to mind is being able to describe a relationship with another serializer

``` elixir
has_one UserSerializer, as: "author"
has_many CommentSerializer, as: "comments"
```

**Comment by benfalk** [comment]
I also would like to see this supported somehow https://github.com/AgilionApps/ja_serializer/issues/45

I think perhaps something like this?

``` elixir
has_one :author, link_only?: true, related: "/users/:user_id"
has_many :comments, link_only?: &Mod.arity/2, related: "/post/:id/comments"
```

**Comment by alanpeabody** [comment]
Thanks @benfalk, replies to all three much appreciated feedback comments:

I like the idea of links being structures, but I would like the callback and relationship definition to be easy to use. I am concerned that it would add another API layer that would cause confusion and require more support and documentation.

I like the "describe" with a serializer approach, that is definitely something we can look into. We just need to continue to support scenarios when there is not a corresponding serializer.

I have actually been thinking the complex cases are better served by letting people override the behaviour callback rather then adding more to the macro DSL.

For example the situation described in 45 could be handled like:

```elixir
def relationships(post, conn) do
  %{
    comments: comment_relationship(post, conn)
  }
end

defp comment_relationshiop(post, %{assigns: %{include_comments: true}}) do
  %JaSerializer.Relationship.HasMany{
    data: post.comments
  }
end

defp comment_relationshiop(post, _) do
  %JaSerializer.Relationship.HasMany{
    related: &post_comment_url(&2, &1.id)
  }
end
```

**Comment by benfalk** [comment]
> We just need to continue to support scenarios when there is not a corresponding serializer.

Perhaps we could fall-back to a pre-defined serializer for conjure one up at compile time that does the bare minimum

**Comment by swr** [comment]
I like the above thinking. I too am running into a "default case" of I'd like to return a list of resource ids but sometimes I'd like to be able to pass in an include and get it side loaded. This is especially true if I want to let the client side determine what all data it wants rather than determining that server side.

Let me know if there is anything I can do to help.

**Comment by benfalk** [comment]
I've been working on some ideas in a couple other repositories to kick up some thoughts.  One of the big breakthroughs I had was getting a way to use the anon functions in a DSL:

https://github.com/benfalk/funky_func/blob/master/test/funky_example_test.exs
:point_up: here I was able to get anon methods converted dynamically into methods to use

:point_down: Here is the code work I've done to explore perhaps re-writing the serializer from the ground up
https://github.com/benfalk/json_api

I may be going a bit to deep in it; however, I'm close be being able to make the following example test work with it:
``` elixir
  defmodule User do
    use JSON.API
    type "user"
    attributes [:name]
    has_many :ponies, type: "pony", where: &(&1.class == "pony"), from: :animals
  end
```

**Comment by alanpeabody** [comment]
@swr thanks for the feedback, I do want to point you to the current `include` support (which is not well documented):

Given:

```elixir
defmodule MyApp.PostView do
  use MyApp.Web, :view
  use JaSerializer.PhoenixView

  attributes [:title, :body]

  has_many :comments, serializer: MyApp.CommentView
end

defmodule MyApp.CommentView do
  use MyApp.Web, :view
  use JaSerializer.PhoenixView

  attributes [:body]
end
```

In your controller you can pass in an "include" option to have the comments included or not:

```elixir
defmodule MyApp.PostController do
  # ...
  def index(conn, %{"include" => "comments"}) do
    posts = Repo.all(Post) |> Repo.preload(["comments"])
    render(conn, :index, data: posts, opts: [include: "comments"])
  end

  def index(conn, _) do
    posts = Repo.all(Post)
    render(conn, :index, data: posts)
  end
  # ...
end
```

Then `GET /posts/` should not have the comments sideloaded, while `GET /posts/?include='comments'` should include the comments.

You would probably want to think about optimizing the logic a bit, but that should get you pointed in the general direction while this RFC is still a WIP.

**Comment by alanpeabody** [comment]
@benfalk looking good. FWIW, I am currently going to just try to get a behaviour callback and struct in place for the relationships without changing the DSL. That will at least allow some of the benefits as described above. I do think changing the DSL to be less confusing and more consistently documented would be a good thing.

I am also looking forward to how your work on funky_funk turns out, as well as some of the ideas around using tuples.

**Comment by benfalk** [comment]
@alanpeabody thanks!  Moving some of the mind bending stuff out into it's own lib seemed like a more sane approach.  I was messing around a lot to get the anonymous methods working and putting that work into it's own lib helped focus on actual logic play.

So far the tuple message structure I've been cooking up seems to work pretty well, still probably have a good week of thinking and tweaking before it's done though.  The main idea behind it is all of the normal logic is covered in a central area that should need to be repeated; and instead only the code you need to worry about is handled - similar to how GenServer and the other OTP behaviors work.  My goal for the end of this week is to have a better understanding of what kinds of "messages" will be needed for the different relations.

Took a look at your wip, looking good :+1:
