### ISSUE TITLE
Ecto 2.0 support

### ISSUE THREAD

**Issue by bjz** [AgilionApps/ja_serializer#112]
Ok, so the [Ecto 2.0.0-rc is out](http://blog.plataformatec.com.br/2016/04/ecto-2-0-0-rc-is-out/). Would it be much trouble to get ja_serializer up and running with it? There are some features we would really love to use in the new Ecto version :)

**Comment by bjz** [comment]
I can make a PR in preparation, but I'm not sure how far off Ecto is to releasing. Also both Scrivener and Poison also depend on Ecto being updated.

**Comment by bjz** [comment]
Ok, I've made a PR to Scrivener to add support for Ecto 2.0.0-rc (see drewolson/scrivener#36). I'll just work off the [cultureamp branch](https://github.com/cultureamp/scrivener/tree/update-to-ecto-2.0.0-rc) for now, and make a PR. As I said on the Scrivener PR, I don't expect it to be merged, but perhaps some people might find it useful!

**Comment by alanpeabody** [comment]
Hi @bjz thanks for opening this issue.

The existing codebase should work just fine with Ecto 2.0+, In all honestly I would like to get rid of the dependency completely if I can figure out how.

Until 2.0 is actually released you can just override the ecto dep in your project:

```elixir
{:ecto, "2.0.0-rc5", override: true}
```

You can probably do the same with scrivener, but I haven't upgraded a project using scrivener to ecto 2.0 yet.

**Comment by bjz** [comment]
Oh cheers, didn't know about dependency overrides. Still getting a handle on mix! It does seem that there is a branch out for scrivener that supports ecto 2.0: https://github.com/drewolson/scrivener/pull/36#issuecomment-222672070

**Comment by bjz** [comment]
I'll try that tomorrow tomorrow at work, then let you know how it goes.

**Comment by bjz** [comment]
This seems to work:

```elixir
  defp deps do
    [
      {:ecto, "~> 2.0.0-rc", override: true},
      {:phoenix_ecto, "~> 3.0.0-rc"},
      {:scrivener, git: "https://github.com/drewolson/scrivener.git", branch: "v2", override: true},
      # ...
    ]
  end
```

**Comment by alanpeabody** [comment]
Great!

**Comment by alanpeabody** [comment]
Now that 2.0 is out this shouldn't be an issue!
