### ISSUE TITLE
Add relationship without preloading it

### ISSUE THREAD

**Issue by lasseebert** [AgilionApps/ja_serializer#117]
Thanks for a great package :)

I want to render a relationship without including the related data (in the `included` field).

Take for example this view:

```elixir
defmodule MyApp.CommentView do
  attributes [:body]
  def type, do: "comments"

  has_one :post,
    include: false,
    serializer: MyApp.PostView
end
```

So I would like to include the `post` in the `relationships` of my comment, but not in `included`. The relationship should just contain the `id` and the `type` of the post. Is this possible without preloading the post relation from the comment?

I already have the `comment.post_id` and `MyApp.PostView` knows the `type` of post, so all the data is available without preloading.

**Comment by alanpeabody** [comment]
Yup, you can pass in type and field:

```elixir
has_one :post, type: "post", field: :post_id
```

Working on better documentation around the relationships now. Please re-open if you have anymore issues.

**Comment by lasseebert** [comment]
This sounds like exactly what I need, thanks.
