### ISSUE TITLE
"type" should be pluralized?

### ISSUE THREAD

**Issue by jordpo** [AgilionApps/ja_serializer#118]
I noticed that the JSON API spec has the value associated with "type" in the response data pluralized and that is what the latest Ember JSON API serializer uses as well. I wasn't sure if there is another reason why this defaults to the singular usage.

**Comment by alanpeabody** [comment]
Hey @jordpo !!!!

Honestly it just seemed more natural to be singular, and it was what ember supported at the time. Phoenix also using all singular module names makes it easy to infer a default singular type.

I suppose we could make it a config option as long as we don't break backwards compatibility, although I was hoping to drop the `inflex` dependency all together with 1.0.

**Comment by jordpo** [comment]
Thanks @alanpeabody! 

We just noticed it on an Ember - Phoenix project we are currently working on and I was just curious as the JSON API spec is still fairly new to me. 

I kind of like the idea of making it an explicit setting in the module, probably as a module attribute? Feels more aligned that way with what I have experienced thus far with Phoenix and the direction that they are taking. 

Love the library though! Setting up resources and having them just work with an Ember UI is pretty awesome. 💯

**Comment by alanpeabody** [comment]
@jordpo you can use the `type/0` callback to customize the return value on each serializer:

https://hexdocs.pm/ja_serializer/0.9.0/JaSerializer.Serializer.html#c:type/0

**Comment by yordis** [comment]
@jordpo from the spec

> Note: This spec is agnostic about inflection rules, so the value of type can be either plural or singular. However, the same value should be used consistently throughout an implementation.

That means, all the examples are in plural but it doesn't have to be like that.

I tried to actually be a little bit strict and I would say that I prefer singular over plural. Follow this link about my opinion http://discuss.jsonapi.org/t/why-the-type-is-in-plural/216/5

**Comment by codyjroberts** [comment]
I ran into the same issue on my Ember/Phoenix project.  Having a singular type makes the most sense to me.  I think this pluralization option should be implemented on the Ember Data side of things. Ember is the proponent of the spec and if the spec is agnostic there should be an option there.  There's probably an easy way to change the adapter, but I haven't figured it out yet.

**Comment by alanpeabody** [comment]
FYI: the `type/0` hooks still works, but I would prefer `type/3` once 0.10.0 gets released.

**Comment by alanpeabody** [comment]
@jordpo @codyjroberts On the ember side I think it is just re-defining this function in your application adapter: 

http://emberjs.com/api/data/classes/DS.JSONAPISerializer.html#method_modelNameFromPayloadKey

**Comment by alanpeabody** [comment]
Closing this for now, I think the default to singular makes sense for Phoenix.

**Comment by dustinfarris** [comment]
If anyone else stumbles on this, here is how to override in your Ember serializer:

```js
// app/serializers/application.js

import JSONAPISerializer from 'ember-data/serializers/json-api';
import { singularize } from 'ember-inflector';

export default JSONAPISerializer.extend({
  payloadKeyFromModelName(modelName) {
    return singularize(modelName);
  }
});
```

**Comment by alanpeabody** [comment]
Thanks!

**Comment by bcardarella** [comment]
It would be great if there was a global opt-in for pluralized types:

```elixir
config :ja_serializer, %{
  pluralize_types: true
}
```

**Comment by bcardarella** [comment]
Before the response of "you can add a global opt-in for the Ember side" is offered here is my counter-point: adding bytes to the client shouldn't be encouraged. That is a cost that each user much incur. Regardless of how small that may be, if this is something that can be handled server-side instead it should be handled server-side.

**Comment by bcardarella** [comment]
If it is OK I can PR this

**Comment by yordis** [comment]
@bcardarella definitely this should be handle in the server side, this is not responsibility of any client realistically

**Comment by bcardarella** [comment]
Got bored, PR'd: https://github.com/vt-elixir/ja_serializer/pull/225/files
