### ISSUE TITLE
Specify relationships to be included.

### ISSUE THREAD

**Issue by alanpeabody** [AgilionApps/ja_serializer#12]
http://jsonapi.org/format/#fetching-includes

likely means a new relationship key such as `optional_include`.

**Comment by green-arrow** [comment]
Do you have any thoughts on how you want this to work? After looking over things, my thought was to pass the comma separated list of includes directly to the `format` method of the serializer, and take things from there.

**Comment by alanpeabody** [comment]
I had started on this a while ago: https://github.com/AgilionApps/ja_serializer/compare/include-param

I haven't had an opportunity to get back to it, but here are some thoughts if you want to pick this up:

I think it makes sense to pass includes in as an option to the format method. I am not sure if it should be passed in as the raw string or as pre-parsed options.

2nd level includes are much more complicated (see the `comments.author` in the [example](http://jsonapi.org/format/#fetching-includes)). I am not particularly proud or happy with the existing include logic, and I foresee this making it more complicated.

The sparse attributes (fields) param should end up with an extremely similar API and some similar implementation details.
