### ISSUE TITLE
If a model contains an attribute `type` it gets used as the resource type.

### ISSUE THREAD

**Issue by jerel** [AgilionApps/ja_serializer#130]
I just updated to latest on master from 4d949cd21 and my resource type behavior is no longer correct. I have `attributes` defined like this: `attributes = [:name, :alias, :type]` in a PhoenixView and ja_serializer is using the value from the `type` attribute as the resource type. If I define a `type/2` introduced in d1a453dc59ed21bf8461fc0f8e3eb9b6ab75c685 then its returned value gets used for the resource but it is also used for the attribute value.

**Comment by alanpeabody** [comment]
Oh, yeah, you are absolutely right.

I am honestly not really sure what to do about this, as I think changing type/0 to type/2 was important for consistency.

If you only have this in a few places I might suggest just not using the attributes/1 macro and instead use the attributes/2 callback:

```elixir
def attributes(struct, _conn), do: Map.take(struct, [:name, :alias, :type])
```

**Comment by jerel** [comment]
Thanks, this is a nice enough solution. Would it be good to call out the naming conflict with the solution in the documentation? Happy to add it if you want it done.

Also, on the topic of documentation: although probably simple it's non-obvious to me how one would render with a different serializer in Phoenix. Given this example: `render(conn, :show, data: article)` what if I want to do something like `render(conn, ArticleWithoutRelationships, data: article)`? Is that possible?

**Comment by alanpeabody** [comment]
Sure, noting that none of the callbacks can be used as attributes would be good. We could probably enforce that at compile time in the macro too.

**Comment by alanpeabody** [comment]
To follow up on your second question, if you have an alternative view you can use https://hexdocs.pm/phoenix/Phoenix.Controller.html#render/4 to render to that view instead.

If your goal is to just not include (sideload) relationships you can look at using the serializer, link, and identifiers: :when_included option. An example might look like this:

```elixir
has_many :comments,
  serializer: CommentView,
  identifiers: :when_included,
  link: "/comments?filter[post]=:id"
```

to include it then just pass the include option:

```elixir
render(conn, data: article, opts: [include: "comments"])
```

**Comment by deadtrickster** [comment]
is there any way to define render has_many relationship without preloading if all I want is just related link?

**Comment by alanpeabody** [comment]
@deadtrickster yes, see: https://hexdocs.pm/ja_serializer/JaSerializer.DSL.html#has_many/2

The "Link based relationships" section has what you are looking for.

**Comment by deadtrickster** [comment]
@alanpeabody Hey, thank you for the reply. I think I should be more specific. I want link AND optional including/sideloading. if I have serializer: option set respective relationship must be preloaded even if include: is turned off. Like if my preloading is costly and I really want to do it when user explicitly asks for inclusion.

**Comment by alanpeabody** [comment]
@deadtrickster you can add the link, and add `indentifiers: :when_included`, that should only require pre-load when the include is requested via the `include` render/format option.

**Comment by deadtrickster** [comment]
yea I'm doing precisely this:

```elixir
  has_many :comments,
    serializer: CommentView,
    identifiers: :when_included,
    link: "/api/v1/comments?filter[user]=:id"
```

end when serializer option is present  I'm required to preload.

**Comment by alanpeabody** [comment]
does your render look something like this?

`render(conn, data: comments, opts: [include: "notcomments"])`

**Comment by deadtrickster** [comment]
```render(conn, "index.json", users: users, opts: [meta: meta_data, include: "comments"])``` or ```render(conn, "index.json", users: users, opts: [meta: meta_data])``` depending on include param precense. Moreover I just noticed identifiers rendered even when ```
    identifiers: :when_included``` is present but not `include:`.

**Comment by alanpeabody** [comment]
Try passing an empty string in the second case. I have been treating includes more like opt out as opposed to opt in, it may be something to update.

**Comment by deadtrickster** [comment]
Yep, include: "" (not obvious though :-( ) does the trick. Thanks! 
btw from jsonapi spec I always thought includes are opt-in (they use word MAY).

**Comment by alanpeabody** [comment]
I will look at adding a default "don't" include when include: false/nil.

**Comment by deadtrickster** [comment]
Cool thank you so much for the help!
