### ISSUE TITLE
Question about JSON-API spec

### ISSUE THREAD

**Issue by timrourke** [AgilionApps/ja_serializer#136]
In the documentation, there is a line under this heading [regarding the `include` option](https://github.com/AgilionApps/ja_serializer#include) that I think may be incorrect regarding the way the JSON-API spec should be implemented:

> Note: If specifying the include option, all "default" includes will be ignored, and only the specified relationships included, per spec.

That does not seem correct; I agree that related objects not indicated in the `?inlcude=foo,bar.baz` query param should not be sideloaded and included within the `included` key of the json payload, but I do _not_ think that those said relationships should be stripped out of the `relationships` key of the primary objects returned.

For example, if I make a GET request to `/api/gradient-layers` with no query params, I get this:

```
{
	"jsonapi": {
		"version": "1.0"
	},
	"data": [{
		"type": "gradient-layers",
		"relationships": {
			"gradient-stops": {
				"data": [{
					"type": "gradient-stops",
					"id": "1"
				}]
			},
			"gradient": {
				"data": {
					"type": "gradients",
					"id": "8"
				}
			}
		},
		"links": {
			"self": "/gradient-layers/1"
		},
		"id": "1",
		"attributes": {
			"updated-at": "2016-07-09T11:30:43Z",
			"order": 0,
			"inserted-at": "2016-07-09T11:30:43Z",
			"gradient-type": "linear",
			"angle": "45"
		}
	}]
}
```

That seems fine and dandy. Note that my `gradient-stops` key under `relationships` is nicely populated with a resource identifier object.

However, now I make a GET request to `/api/gradient-layers?include=gradient` and I get the following payload:

```
{
	"jsonapi": {
		"version": "1.0"
	},
	"included": [{
		"type": "gradients",
		"relationships": {
			"user": {
				"data": {
					"type": "users",
					"id": "1"
				}
			},
			"gradient-layers": {
				"links": {
					"related": "/gradients/8/gradient-layers"
				}
			}
		},
		"links": {
			"self": "/gradients/8"
		},
		"id": "8",
		"attributes": {
			"updated-at": "2016-07-04T14:11:49Z",
			"title": "my fake gradient",
			"permalink": "fake-permalink",
			"inserted-at": "2016-07-04T14:11:49Z",
			"description": "This is a fake gradient description",
			"body-autoprefixed": "fake autoprefixed body",
			"body": "fake body"
		}
	}],
	"data": [{
		"type": "gradient-layers",
		"relationships": {
			"gradient-stops": {},
			"gradient": {
				"data": {
					"type": "gradients",
					"id": "8"
				}
			}
		},
		"links": {
			"self": "/gradient-layers/1"
		},
		"id": "1",
		"attributes": {
			"updated-at": "2016-07-09T11:30:43Z",
			"order": 0,
			"inserted-at": "2016-07-09T11:30:43Z",
			"gradient-type": "linear",
			"angle": "45"
		}
	}]
}
```

Note that my `included` key contains the correct sideloaded relationship, but in the primary `data` key, my  first `gradient-layer` entity's `gradient-stops` key is no longer populated with anything.

[Per the JSON-API spec:](http://jsonapi.org/format/#fetching-includes)

> If an endpoint supports the include parameter and a client supplies it, the server MUST NOT include unrequested resource objects in the *included* section of the compound document.

The spec does _not_ say that the related object should be omitted from the `relationships` key of the primary data object if it is not explicitly included in the `include` query param, only that it should be omitted from the `included` key.

Am I perhaps doing something wrong in implementing the relationships here? Here's what my relevant code looks like:

_...in gradient_layer_controller.ex:_

```
def index(conn, %{"include" => include}) when include != "" do
    rel_string = String.replace(include, "-", "_")

    gradientLayers = 
      rel_string
      |> String.split(",")
      |> Enum.filter(fn value -> value in @relationships end)
      |> Enum.map(fn value -> String.to_atom(value) end)
      |> gradient_layer_query
      |> Repo.all

    render(conn, "index.json", data: gradientLayers, opts: [include: rel_string])
  end

defp gradient_layer_query(value) do 
    from gl in GradientLayer, preload: [^value]
end
```

_...in gradient_layer_view.ex:_

```
  has_many :gradient_stops,
    type: "gradient-stops",
    serializer: Colorstorm.GradientStopView,
    include: false

  def gradient_stops(gradientLayer, conn) do
    include = Map.get(conn.params, "include")
    cond do
      include && "gradient-stops" in String.split(include, ",") ->
        Map.get(gradientLayer, :gradient_stops)
      true ->
        query = from gs in Colorstorm.GradientStop,
          select: gs.id,
          where: gs.gradient_layer_id == ^gradientLayer.id
        Colorstorm.Repo.all(query)
    end
  end
```

I strongly suspect that I'm overlooking something obvious here, I'm a complete newb when it comes to Elixir and Phoenix. Absolutely love ja_serializer! Couldn't live without it. Thanks! :)

**Comment by timrourke** [comment]
Hm, just noticed that the missing `gradient-stops` relationship data _could_ be missing because I needed to turn on the following flag in my view:

```
 has_many :gradient_stops,
    type: "gradient-stops",
    serializer: Colorstorm.GradientStopView,
    identifiers: :always, # <- This option was missing before
    include: false
```

Adding that `identifiers` option seems to ensure the resource identifiers are included regardless of the `include` param.

**Comment by alanpeabody** [comment]
Yup, your last comment got it. You could also use a link if you wanted to avoid the extra query.

Unfortunately the inclusion part of the spec is by far the most complicated and confusing. I would be very appreciative of any PRs improving the documentation around this!

If you have any other questions let me know, otherwise I am going to close this for now.

**Comment by timrourke** [comment]
Awesome, thanks @alanpeabody!
