### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by gordonbisnor** [AgilionApps/ja_serializer#14]
I'm new to Elixir and have been attempting to convert a Rails Active Model Serializers API to a Phoenix as a learning experiment. 

I started out manually building JSON using Poison and views. It was blazing fast but becoming tedious to build out in full doing everything manually. I heard about ja_serializer and have been trying to set it up in the application.

Everything is working wonderfully with speed being the one problematic issue –– I'm finding that the same API endpoints in my Rails application are rendering at about ~ 24x faster, for example, than my Phoenix API when using ja_serializer.

Wondering if you have any thoughts on performance –– is the library in its infancy still and not yet optimized for performance? Or is lit more likely that I have something configured poorly etc? 

As an example:
Rails: 178ms, 1.6ms in ActiveRecord
Phoenix: Sent in 4102ms, 4.7ms spent on queries (seemed like each individual field that I add to the JSON result is adding about 300ms to the send time)

If there is anything I can do. I have a rudimentary of Elixir at this point, but would be happy to pitch in if possible.

**Comment by alanpeabody** [comment]
Hey @gordonbisnor thanks for opening an issue!

Performance is definitely a hugely important issue, but not something I have spent any time on.

That said my serializers with ~15 attributes are still seeing sub 100ms responses so I have had reason to look at it.

Can you give me a bit more insight into how many models and attributes you are serializing? I will start looking though the code for any slow points, but I can't promise I will come up with anything until I have a bit of time this weekend or next week to really dig in.

**Comment by alanpeabody** [comment]
@gordonbisnor I did some digging and found some pretty serious performance issues locally. Thanks for bringing this to my attention!

In particular the formatting protocol was not defining an implementation for basic data types such as strings and integers. Falling back to the Any protocol for serializing these was really slow.

I would love if you could give this branch a try and let me know if you see improvement: https://github.com/AgilionApps/ja_serializer/tree/v0.1.x

I tried to push a 0.1.2 release this evening but having some connection issues w/ hex. I will try again in the morning.

**Comment by gordonbisnor** [comment]
@alanpeabody Thanks for the response, that sounds promising! Will try it out and post.

**Comment by alanpeabody** [comment]
@gordonbisnor okay, 0.1.2 has the fix, I will port it to master tonight. Some types such as maps/tuples and other formats will continue to be a little slower, but binaries, strings and numbers should be much faster. I am going to keep thinking about the best way to handle this while allowing custom formatting values.

**Comment by gordonbisnor** [comment]
@alanpeabody -- those fixed made a massive difference for my application. 

My endpoint times are not entirely fair because I have yet to place some of the same limitations on associations etc that I have in my original implementation just using Poison.

That said – all of my endpoints came in at these total times:
*Poison:* 218ms
*Older version of JA serializer master:* 9s 263ms
*Updated JA serializer:* 1s150ms

I assume that I could get that 1s150ms down substantially by optimizing associations etc.

**Comment by alanpeabody** [comment]
@gordonbisnor that is great, but lets do better!

Are you serializing any attributes values besides strings, floats, integers, or atoms (or lists of those things)? If so those other values are not optimized and will still underperform. Of particular note is Ecto dates/times and Decimals.

I haven't added this to this repository (yet) as I have not started adding Ecto support but adding this to your repository will improve performance in the meantime if using Ecto dates:

```elixir
defimpl JaSerializer.Formatter, for: [Ecto.Date, Ecto.Time, Ecto.DateTime] do
  def format(dt), do: dt
end
```

If you are serializing Maps, Decimals, or anything else implementing the protocol for those will help as well.

**Comment by gordonbisnor** [comment]
@alanpeabody Yes I was using times and dates and added the additional code you mentioned. Between that and optimizing the associations, the total for all  endpoints is now down to ~99ms which is a massive change!

**Comment by alanpeabody** [comment]
Awesome glad to hear it! Let me know if you run into any other issues or have any other feedback.

**Comment by greyhwndz** [comment]
@alanpeabody are there updates ja_serializer that improved the performance at this time?

**Comment by alanpeabody** [comment]
@greyhwndz There have been some improvements to performance throughout the lifetime of the project. If you find something you think is slower then it should be please open an issue.

One thing I will say is that the DSL for attributes is typically slower then then attributes/2 callback.
