### ISSUE TITLE
`include` for has_one not working

### ISSUE THREAD

**Issue by dustinfarris** [AgilionApps/ja_serializer#140]
Not sure if this is a bug or not.  Seems like it might be user error.  But..

My UserView:

```ex
defmodule MyApp.UserView do
  use MyApp.Web, :view
  use JaSerializer.PhoenixView

  alias MyApp.Repo

  attributes [:email, :inserted_at, :updated_at]

  has_one :tenant,
    serializer: MyApp.TenantView,
    include: true

end
```

TenantView:

```ex
defmodule MyApp.TenantView do
  use MyApp.Web, :view
  use JaSerializer.PhoenixView

  attributes [:name, :domain, :inserted_at, :updated_at]
end
```

And in UserController:

```ex
def current(conn, _) do
  user = Guardian.Plug.current_resource(conn) |> Repo.preload(:tenant)

  conn
  |> render("show.json-api", data: user)
end
```

The tenant shows up in `"relationships"` on the JSON API response body, but `"included"` is not there.  Am I missing something obvious?  Or is this perhaps broken?

**Comment by dustinfarris** [comment]
User error :-(

**Comment by bmrsny** [comment]
@dustinfarris I know this was from a year ago, but was curious if you could share what your User Error was, if you can remember? I am having the same issue. Thanks.

**Comment by dustinfarris** [comment]
Sorry, I don't remember :(
