### ISSUE TITLE
dont remove "json" content-type, remove the warning

### ISSUE THREAD

**Issue by izelnakri** [AgilionApps/ja_serializer#142]
What is the purpose of forcing people to use "json-api" content-type instead of json? Google chrome automatically downloads those links as files instead of parsing them on the page as json. I think this is a big bummer: https://github.com/AgilionApps/ja_serializer/blob/master/lib/ja_serializer/phoenix_view.ex#L64

**Comment by alanpeabody** [comment]
@izelnakri thank you for opening an issue.

At this point my opinion is that supporting API clients and the JSON-API spec takes precedence over supporting humans via browsers. Tools like curl and postman are great if you just want to visually verify an API response.

The reason for the deprecation is to ensure that people building json-api's don't accidentally emit non-conforming responses.

If you want to return json I suggest not using the built in JaSerializer.PhoenixView and instead defining your own, something like:

```elixir
defmodule MyApp.PostView do
  use MyApp.Web, :view
  use JaSerializer

  attributes [:title, :body]

  def render(view, data) when view in ["index.json", "show.json"] do
    JaSerializer.format(__MODULE__, data[:data], data[:conn], data[:opts] || [])
  end
end
```

**Comment by alexparker** [comment]
I'm also curious about this issue. I get the warning when I render via the code:
`render(conn, :index, data: models)`

But i in fact don't have "index.json" anywhere. Should this still be the case?
