### ISSUE TITLE
Rendering bare resource objects

### ISSUE THREAD

**Issue by bcardarella** [AgilionApps/ja_serializer#143]
I've been working on a json-api assertion library. I'd like to support ja_serializer but a few things are making it more difficult. Specifically how ja_serializer handles relationship data for resource objects.

Currently ja_serializer will raise an error if relationships aren't preloaded. I'd advocate for an option to skip this. Or perhaps not raise at all?

**Comment by alanpeabody** [comment]
@bcardarella, just found that library the other day, excited to try it out and clean up a lot of test verbosity.

I am open to tweaking relationships, I have currently defaulted to behaving like ecto (eg no eager loading). The risk of not raising by default is people confused around missing relationships. I could see an option to skip if not loaded. What do you think a good API for that might look like?

 I have also been toying with a preload/2 hook that would get fired for either the collection or single struct being serialized. It would be a place to call Repo.preload, but only called on the top level collection or struct being serialized.

**Comment by bcardarella** [comment]
Ideally all we'd need is a way to force the serializer to return a bare resource object. If you are open to it I can add support for a `bare: true` option on the context which will prevent relationships and includes from being rendered.

If this feels like a hack then I'm happy to do a hangout this week to discuss a better solution.
