### ISSUE TITLE
Error when use serializer with field

### ISSUE THREAD

**Issue by diegonogueira** [AgilionApps/ja_serializer#146]
Hi,
I have a has_one like this:

```elixir
has_one :project,
    serializer: FlowsApi.ProjectView,
    #identifiers: :when_included,
    include: false,
    field: :project_id
```

`/tasks/690bffff-a0d3-4ce9-9045-ab0137fb0f1c`

```json

  "jsonapi": {
    "version": "1.0"
  },
  "data": {
    "type": "task",
    "relationships": {
      "project": {
        "data": {
          "type": "project",
          "id": "7b6a679d-7d63-470d-b7bc-64b20c7ace4f"
        }
      }
    },
    "id": "690bffff-a0d3-4ce9-9045-ab0137fb0f1c",
    "attributes": {
      "name": "Task 2.1"
    }
  }
}
```

But, if I add include:

`/tasks/690bffff-a0d3-4ce9-9045-ab0137fb0f1c?include=project`

```
error] #PID<0.1113.0> running FlowsApi.Endpoint terminated
Server: docker:4000 (http)
Request: GET /api/tasks/690bffff-a0d3-4ce9-9045-ab0137fb0f1c?include=project
** (exit) an exception was raised:
    ** (BadMapError) expected a map, got: "7b6a679d-7d63-470d-b7bc-64b20c7ace4f"
        (stdlib) :maps.find(:id, "7b6a679d-7d63-470d-b7bc-64b20c7ace4f")
        (elixir) lib/map.ex:131: Map.get/3
        (ja_serializer) lib/ja_serializer/builder/resource_object.ex:20: JaSerializer.Builder.ResourceObject.build/1
        (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
        (ja_serializer) lib/ja_serializer/builder/included.ex:37: JaSerializer.Builder.Included.resource_objects_for/4
        (ja_serializer) lib/ja_serializer/builder/included.ex:60: JaSerializer.Builder.Included.resources_for_relationship/4
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ja_serializer) lib/ja_serializer/builder/included.ex:30: JaSerializer.Builder.Included.do_build/4
        (ja_serializer) lib/ja_serializer/builder/included.ex:15: JaSerializer.Builder.Included.build/2
        (ja_serializer) lib/ja_serializer/builder/top_level.ex:27: JaSerializer.Builder.TopLevel.build/1
        (ja_serializer) lib/ja_serializer.ex:59: JaSerializer.format/4
        (phoenix) lib/phoenix/view.ex:335: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:641: Phoenix.Controller.do_render/4
        (flows_api) web/controllers/task_controller.ex:1: FlowsApi.TaskController.action/2
        (flows_api) web/controllers/task_controller.ex:1: FlowsApi.TaskController.phoenix_controller_pipeline/2
        (flows_api) lib/flows_api/endpoint.ex:1: FlowsApi.Endpoint.instrument/4
        (flows_api) lib/phoenix/router.ex:261: FlowsApi.Router.dispatch/2
        (flows_api) web/router.ex:1: FlowsApi.Router.do_call/2
        (flows_api) lib/flows_api/endpoint.ex:1: FlowsApi.Endpoint.phoenix_pipeline/1
        (flows_api) lib/plug/debugger.ex:93: FlowsApi.Endpoint."call (overridable 3)"/2
```

If I remove the field option:

```elixir
has_one :project,
    serializer: FlowsApi.ProjectView,
    #identifiers: :when_included,
    include: false#,
    #field: :project_id
```

`/tasks/690bffff-a0d3-4ce9-9045-ab0137fb0f1c?include=project` Works!

But, without include..

```
error] #PID<0.1205.0> running FlowsApi.Endpoint terminated
Server: docker:4000 (http)
Request: GET /api/tasks/690bffff-a0d3-4ce9-9045-ab0137fb0f1c
** (exit) an exception was raised:
    ** (JaSerializer.AssociationNotLoadedError) The project relationship returned %Ecto.Association.NotLoaded{}.

Please pre-fetch the relationship before serialization or override the
project/2 function in your serializer.

Example:

    def project(struct, conn) do
      case struct.project do
        %Ecto.Association.NotLoaded{} ->
          struct
          |> Ecto.assoc(:project)
          |> Repo.all
        other -> other
      end
    end
```

When I add identifiers: :when_included:

```elixir
  has_one :project,
    serializer: FlowsApi.ProjectView,
    identifiers: :when_included,
    include: false#,
    #field: :project_id
```

`/tasks/690bffff-a0d3-4ce9-9045-ab0137fb0f1c?include=project` Works!

`tasks/690bffff-a0d3-4ce9-9045-ab0137fb0f1c` Works, but does not return identifier.. 

```
{
  "jsonapi": {
    "version": "1.0"
  },
  "data": {
    "type": "task",
    "relationships": {
      "project": {}
    },
    "id": "690bffff-a0d3-4ce9-9045-ab0137fb0f1c",
    "attributes": {
      "name": "Task 2.1"
    }
  }
}
```

I'm trying a way to add include returns included and without include returns data:
```
relationships": {
      "project": {
        "data": {
          "type": "project",
          "id": "7b6a679d-7d63-470d-b7bc-64b20c7ace4f"
        }
      }
```

Am I doing something wrong?

thks,

**Comment by alanpeabody** [comment]
For now I would just suggest using:

`has_one :project, serializer: FlowsApi.ProjectView`

and always pre-loading the project in your controller.

Alternatively you could use 

```
has_one :project,
    serializer: FlowsApi.ProjectView,
    identifiers: :when_included

**Comment by diegonogueira** [comment]
Ok, Thanks!

**Comment by diegonogueira** [comment]
I created this workaround to avoid the error:

```
    ** (BadMapError) expected a map, got: "7b6a679d-7d63-470d-b7bc-64b20c7ace4f"
        (stdlib) :maps.find(:id, "7b6a679d-7d63-470d-b7bc-64b20c7ace4f")
        (elixir) lib/map.ex:131: Map.get/3
        (ja_serializer) lib/ja_serializer/builder/resource_object.ex:20: JaSerializer.Builder.ResourceObject.build/1
```

ProjectView

```elixir
  def project(struct, conn) do
    case struct.project do
      %Ecto.Association.NotLoaded{} -> %FlowsApi.Project{id: struct.project_id}
      other -> other
    end
  end
```

Now **without** include=project returns 

```json
      "project": {
        "data": {
          "type": "project",
          "id": "0d492762-ccb9-47c4-8f92-01ea5b7608f7"
        }
      }
```
And **with** include returns the project data with attributes.

I don't know if it is a bug or I am doing something wrong..

**Comment by alanpeabody** [comment]
Can you describe exactly the results you want and some basics about the data model? It is hard to tell exactly what you are getting at.

**Comment by diegonogueira** [comment]
I want to get this:

/tasks/690bffff-a0d3-4ce9-9045-ab0137fb0f1c

```
  "jsonapi": {
    "version": "1.0"
  },
  "data": {
    "type": "task",
    "relationships": {
      "project": {
        "data": {
          "type": "project",
          "id": "7b6a679d-7d63-470d-b7bc-64b20c7ace4f"
        }
      }
    },
    "id": "690bffff-a0d3-4ce9-9045-ab0137fb0f1c",
    "attributes": {
      "name": "Task 2.1"
    }
  }
}```

And when call with include returns included:

/tasks/690bffff-a0d3-4ce9-9045-ab0137fb0f1c?include=project

**Comment by diegonogueira** [comment]
The version 0.10.1 resolved the problem :)

**Comment by Moxide** [comment]
Hello,
I'm facing exactly the same issue, and I'm forced to use your workaround (thanks !) to get the wanted behavior.

Given the following code :
```User View```
```
  has_one :category,
    serializer: MyApp.CategoryView,
    identifiers: :always,
    field: :category_id,
    type: "category"

  def preload(record_or_records, _conn, include_opts) do
    MyApp.Repo.preload(record_or_records, include_opts)
  end
```
I would expect the following :
- ```api/user/1``` would give :
```
{
  "jsonapi": {
    "version": "1.0"
  },
  "data": {
    "type": "user",
    "relationships": {
      "category": {
        "data": {
          "type": "category",
          "id": "10"
        }
      }
    },
    "id": "1",
    "attributes": {
      "name": "User"
    }
  }
}
```

- ```api/user/1?include=category``` would give :
```
{
  "jsonapi": {
    "version": "1.0"
  },
  "included": [
    {
      "type": "category",
      "id": 10,
      "attributes": {
         "name": "category1",
         "color": "#FF0000"
       }
    }
  ],
  "data": {
    "type": "user",
    "relationships": {
      "category": {
        "data": {
          "type": "category",
          "id": "10"
        }
      }
    },
    "id": "1",
    "attributes": {
      "name": "User"
    }
  }
}

```

The first request succeeds, but the second give the map error : 
```
    ** (BadMapError) expected a map, got: 10
        (stdlib) :maps.find(:id, 10)
        (elixir) lib/map.ex:145: Map.get/3
        (ja_serializer) lib/ja_serializer/builder/resource_object.ex:20: JaSerializer.Builder.ResourceObject.build/1
```

So I have to use the workaround : 
```
  def category(struct, conn) do
    case struct.category do
      %Ecto.Association.NotLoaded{} -> %MyApp.Category{id: struct.category_id}
      other -> other
    end
  end
```

Is there a way to get the desired behavior without having to use this workaround ?
I'm using the great ```ja_resource``` and thanks to it, a lot of boilerplate code is removed, so it feels like a regression to write this workaround code for each relationship !
Thanks ;-)

**Comment by Moxide** [comment]
Actually, this is solved by preloading the relations, but in the case of a not included ```has_one``` relation, we could simply return the 'type' and 'id' without preloading.

**Comment by alanpeabody** [comment]
Yeah... The logic around this is pretty complicated. If you can come up with tests that fail that you think should pass I would be very grateful.

**Comment by yogipatel** [comment]
@alanpeabody I'm running into this issue as well. A `has_one` relationship doesn't need to have its related resource to be loaded in order to serialize it out as a resource identifier. I think it's fair to have that as the default behaviour and only check if the relationship is loaded if the serializer is instructed to include the resource. I hope that makes sense.

I'd be happy to write up a PR. Feels like a pretty simple change, however I only know about my own use cases and I'm sure there are nuances I'm not aware of. Any thoughts on possible complications?

**Comment by alanpeabody** [comment]
@yogipatel The inclusion logic is fairly complicated but is based on my understanding of the spec, in particular:

```
If an endpoint supports the include parameter and a client supplies it, the server MUST NOT include unrequested resource objects in the included section of the compound document.
```

However, it is very possible something is wrong. If we can get some failing tests (or even a full pr) that doesn't change desired behavior I would be very appreciative.

**Comment by yogipatel** [comment]
@alanpeabody I think the key in that part of the spec is resource _objects_. The spec makes a point of differentiating between a resource object and a resource identifier. Included resources are specifically "an array of resource objects".

The `data` section of a relationship object is a resource linkage, which is defined as:

> Resource linkage MUST be represented as one of the following:
> - null for empty to-one relationships.
> - an empty array ([]) for empty to-many relationships.
> - a single resource identifier object for non-empty to-one relationships.
> - an array of resource identifier objects for non-empty to-many relationships

My interpretation is that, for a to-one relationship, the data section must be null or a resource identifier (the third alternative being that the relationship is not specified at all). _Including_ the related resource creates an entry for its corresponding resource object.

Do you agree with that assessment?

**Comment by alanpeabody** [comment]
The `identifier: :always` option on the relationship should ensure resource identifiers are always included. Is that not sufficient?

I am happy to look at PRs that enhance this functionality.

**Comment by nightire** [comment]
@alanpeabody I think the problem is `identifier: :always` forces a preload, but we think this is not necessary, and this is why we have to write a patch like:

```elixir
def project(struct, conn) do
  case struct.project do
    %Ecto.Association.NotLoaded{} -> %FlowsApi.Project{id: struct.project_id}
    other -> other
  end
end
```

this will help us to avoid preload.
