### ISSUE TITLE
"id" attribute cast to string even if it's originally integer

### ISSUE THREAD

**Issue by egilburg** [AgilionApps/ja_serializer#152]
Using ja_serializer 0.10

I get back JSON like this:

```
data: {
  id: "1"
  attributes: {...}
}
```

"id" field is Integer in db, but is force-casted to string. Even defining custom method like this:

```
  def id(object, _) do
    12345
  end
```

Still returns `"12345"` instead of `12345`

**Comment by hunterboerner** [comment]
Json API spec requires that id is a string.

> Every resource object MUST contain an id member and a type member. The
values of the id and typemembers MUST be strings

**Comment by alanpeabody** [comment]
Yup, @hunterboerner nailed it. This is per spec for json-api which is currently the only format we support.
