### ISSUE TITLE
function nil.id/2 is undefined or private

### ISSUE THREAD

**Issue by rlb3** [AgilionApps/ja_serializer#160]
I'm using ja_serializer from phoenix and I'm getting this error when when trying to render the index. I am some what familiar with phoenix but this is my first experiment with ja_serializer so I'm not sure where to start debugging.

<img width="672" alt="screen shot 2016-08-19 at 10 03 37 am" src="https://cloud.githubusercontent.com/assets/8289/17814197/42d87b72-65f4-11e6-9b9a-3604c8928c7b.png">

This is what my controller looks like:

```elixir
defmodule JvavWeb.Api.LineupController do
  use JvavWeb.Web, :controller

  alias JvavWeb.{Lineup, Member}

  def index(conn, _params) do
    lineup = Repo.all(Lineup) |> Repo.preload(:audio) |> Repo.preload(:video) |> Repo.preload(:alternate)
    render(conn,  data: lineup)
  end
end
```

This is what my view looks like.
```elixir
defmodule JvavWeb.Api.LineupView do
  use JvavWeb.Web, :view
  use JaSerializer.PhoenixView

  alias JvavWeb.Repo

  attributes [:date]

  has_one :audio,
    include: true
  # has_one :video,
  #   include: true
  # has_one :alternate,
  #   include: true

  def audio(lineup, _conn) do
    lineup.audio
  end
end
```

And this is what the schema looks like:

```elixir
  schema "lineup" do
    field :date, Ecto.Date
    belongs_to :audio, JvavWeb.Member
    belongs_to :video, JvavWeb.Member
    belongs_to :alternate, JvavWeb.Member

    timestamps()
  end
```

**Comment by alanpeabody** [comment]
Hi @rlb3, in order to include a relationship you must pass the serializer option (a module/view) in the definition. See the has_many docs for examples.

**Comment by rlb3** [comment]
Sorry about that. That works. Thank you.
