### ISSUE TITLE
How to pass format options to Phoenix render function (e.g: "include")

### ISSUE THREAD

**Issue by noam87** [AgilionApps/ja_serializer#168]
Hi, I'm using JA Serialize with Phoenix as per the example in the Readme. However, it does not seem to recognize `?include=user` in the params. Is there a way to pass this through the render function?

```
|> render("show.json-api", role: role)
```

```
defmodule MyApp.Api.V1.RoleView do
  use MyApp.Web, :view
  use JaSerializer.PhoenixView

  location "/users/:user_id/roles/:id"
  attributes [:role_type, :active, :user_id]

  has_one :user,
          links: [related: "/users/:id"]
end
```

**Comment by alanpeabody** [comment]
Hi @noam87,

You can pass include in the opts to render, eg:

`render(conn, :show, data: data, opts: [include: params["include"]])`

However you must:

1) Explicitly preload any required relationships this can be done in your controller or via the `preload/3` callback. https://hexdocs.pm/ja_serializer/0.11.0/JaSerializer.Serializer.html#c:preload/3
2) Provide a serializer option to the included relationship. You can leave the `include` option nil and the param will dictate if it is indeed included or not. https://hexdocs.pm/ja_serializer/0.11.0/JaSerializer.DSL.html#has_many/2

**Comment by alanpeabody** [comment]
Let me know if this doesn't work for you!
