### ISSUE TITLE
Custom key formatting when using scrivener broken.

### ISSUE THREAD

**Issue by edmaarcosta** [AgilionApps/ja_serializer#170]
**Elixir 1.3.2**

I have a project using ja_serializer with scrivener_ecto for pagination, also a config for custom _dasherize_ in config.exs. But this message appears in `mix do deps.get, deps.compile`:

`== Compilation error on file lib/ja_serializer/builder/scrivener_links.ex ==
** (UndefinedFunctionError) function MyApp.Dasherize.dasherize/1 is undefined (module MyApp.Dasherize is not available)
    MyApp.Dasherize.dasherize("page")
    lib/ja_serializer/builder/scrivener_links.ex:8: (module)
`

If I comment the custom config, the compiling happens fine.

This is my config.exs:
```
config :ja_serializer, key_format: {:custom, MyApp.Dasherize, :dasherize}
```

This is my module for custom dasherize:
```
defmodule MyApp.Dasherize do
  def dasherize(key) do
    "__id__" ->
      key
    _ ->
      underscore_to_dash(key)
  end

  defp underscore_to_dash(key), do: String.replace(key, "_", "-")
end
```

This is my mix.exs
```
  defp deps do
    [
     {...},
     {:ja_serializer, "~> 0.10.1"},
     {:scrivener_ecto, "~> 1.0"}
    ]
  end
```

ja_serializer search for dasherize before the module being compiled.

The repo is [here](https://github.com/edmaarcosta/my_app) case required.

**Comment by alanpeabody** [comment]
Thanks for the bug report w/ repo! I will take a look this evening.

**Comment by alanpeabody** [comment]
Okay @edmaarcosta I understand the issue. It was introduced when working on improving performance. I will push out a new version with a fix in the next couple of days.
