### ISSUE TITLE
Indirect Optional Includes with Identifiers

### ISSUE THREAD

**Issue by exitface** [AgilionApps/ja_serializer#173]
Indirect Optional Includes with Identifiers

Not the best title, I know, but hard to explain.

I'm working on a SPA and making use of the new identifiers feature to specify
optional relationship https://github.com/AgilionApps/ja_serializer/pull/121

I'm working with two models

```elixir
defmodule Category do
  has_many :projects, Project
end

defmodule Project do
  belongs_to :category, Category
end

defmodule CategoryView do
  has_many :projects, serializer: ProjectView, include: true, type: :project, identifiers: :when_included
end


defmodule ProjectView do
  has_one :category, serializer: CategoryView, type: :category, include: true,  identifiers: :when_included
end

defmodule CategoryController do
  def index(conn, _params) do
    categories = Repo.all(from c in Category, preload: [projects: :tasks])
    render conn, data: categories, opts: [include: "projects,projects.tasks,projects.tasks.last_time_entry"]
  end
end

defmodule ProjectController do
  def create(conn, %{"project" => project_params}) do
    # ... Creation code

    render("show.json", data: project, opts: [include: "category"])
  end
end
```

On page load I pull all the categories and their projects as includes

It is also possible to create a category when creating a project. When this happens I need access to the newly created category to populate the frontend.

This blows up because the CategoryView in ProjectsView expects to be able to serialize the projects, I'm guessing because I'm not directly passing includes to it?

The only way I've found to work around this is to setting a custom retrieval method that checks to see if the include option was passed and check if that contains the desired relationship

```elixir
defmodule CategoryView do
  has_many :projects, serializer: ProjectView, include: true, type: :project, identifiers: :when_included

  def projects(struct, conn) do
    if String.contains? conn.asssigns[:opts][:include], "projects," do
       nil
    else
      # ... Fetch
    end
  end
end
```

Am I using the feature incorrectly or is there some way to pass the includes to the CategoryView when used an association in the ProjectView?

**Comment by alanpeabody** [comment]
Hey @exitface, thanks for the detailed ticket.

My suggestion is to take a look at the recently added Serialiser.preload/3 callback and see if that meets your needs. Also, the `include` relationship option can be read as `include_by_default`, so if you are only including in some situations I might set that as false and rely on the render include opt to ask for it to be included.

I personally also typically use a `link` in conjunction with optional includes and skip the `type`.

**Comment by alanpeabody** [comment]
@exitface I haven't heard back from you so I will assume you got things figured out!

**Comment by exitface** [comment]
@alanpeabody - Sorry! Very hectic, week, I haven't had a chance to pop back in. First, thanks for your help! The note on `include` is helpful - I was using it under the impression that it had to be used otherwise it would not be added as an include in the response. I think that should solve my issue, thanks again!
