### ISSUE TITLE
JSON API errors (like 404.json-api) require render_errors config in config.exs

### ISSUE THREAD

**Issue by JoshSmith** [AgilionApps/ja_serializer#176]
If you're rendering JSON API errors like so:

```
  def render("404.json-api", _assigns) do
    %{
      id: "NOT_FOUND", 
      title: "404 Resource not found", 
      status: 404
    }
    |> JaSerializer.ErrorSerializer.format
  end
```

Then you _must_ add `json-api` to the `accepts` of `render_errors` in your `config.exs`, like so:

```
config :my_app, MyApp.Endpoint,
  ...
  render_errors: [view: MyApp.ErrorView, accepts: ~w(html json json-api)],
  ...
```

I think we should add this to the documentation, maybe after this point:

> For strict content-type/accept enforcement and to auto add the proper content-type to responses add the JaSerializer.ContentTypeNegotiation plug.

Happy for your thoughts on this before opening a PR.

**Comment by alanpeabody** [comment]
Yeah, looks great!

**Comment by atomkirk** [comment]
Where the heck do I put `def render("404.json-api", _assigns) do` so that it actually gets called?

More specifically, `def render("errors.json-api", _assigns) do`
