### ISSUE TITLE
warning: Elixir.XYI.AddressSerializer.format/3 is deprecated.

### ISSUE THREAD

**Issue by OpakAlex** [AgilionApps/ja_serializer#189]
Here is the best fix for this stupid (fuck so stupid) warning:
```
warning: Elixir.XYI.AddressSerializer.format/3 is deprecated.
Please use JaSerializer.format/4 instead, eg:
JaSerializer.format(Elixir.XYI.AddressSerializer, data, conn, opts)
```

The best fix for this stupid warning:
```
defmodule XYI.AddressView do
  use XYI.Web, :view

  alias XYI.AddressSerializer

  def render("address.json", %{address: address}) do
    JaSerializer.format(XYI.AddressSerializer, address, %{}, [])
  end
end
```

0 warnings.

You can not pass connection to serializer, because serializer just serialize you structure to json, why it needs connection? To make twitts i hope!

Enjoy guys! More stupid deprications and warnings makes this world better.

PS: You can not delete issues on Github :)))

**Comment by alanpeabody** [comment]
@OpakAlex thank you for the extremely polite issue. 👀 

The reason a conn is passed to the serializer is for context. In particular a common use case is that you may render different data based on the current_user.

**Comment by OpakAlex** [comment]
@alanpeabody but name it as `context`.

**Comment by OpakAlex** [comment]
@alanpeabody also why without `context` it's create warning? Put my fix, and remove warning please. And normal people can use it without 2 hours debug this shit issue. Sometimes people needs write software, not drink tea and go to meetings. Ok?
