### ISSUE TITLE
0.3.1 patch release please

### ISSUE THREAD

**Issue by AaronSikes** [AgilionApps/ja_serializer#20]
The fact that ecto is not specified as a dependency in 0.3.0 means that the `ensure_loaded?` check [here](https://github.com/AgilionApps/ja_serializer/blob/master/lib/ja_serializer/ecto_error_serializer.ex#L1) fails, and the EctoErrorSerializer is not available. This is fixed in commit ec28efd4f0fe67cc229ef9da5c20f667e213ebc0, but this has not been released yet. We're currently pulling that commit, rather than a hex release.

**Comment by alanpeabody** [comment]
For some reason I thought I had released this, but I must have forgot, thanks for bringing it to my attention!

Released now:
https://hex.pm/packages/ja_serializer/0.3.1
