### ISSUE TITLE
Passing additional values into Serializer

### ISSUE THREAD

**Issue by pollingj** [AgilionApps/ja_serializer#21]
I'm very new to Elixir, so please excuse my ignorance.

Is there any way to pass in additional data to a Serializer.

For example, if I have 
```
has_one :group, :include MyApp.GroupSerializer
```
in my view I can only pass through the group data here.  If I have a number of users within that group and I want to output the total number of users in a group, so e.g. have a `number_of_users` attribute within the GroupSerializer, I know I can do 

```
def number_of_users(model, _conn) do
Enum.count(model.users)
end
````

However that requires me preloading data both ways users -> groups -> users.  It would just be easier to pass through the additional data from the user view.  Is this possible?  

Hope this makes sense.

**Comment by alanpeabody** [comment]
Without a bit more insight into your exact use case I can offer the following options:

1. Use a counter column to track number of users at write time instead of read time.
2. You can define `users\2` and `group\2` function in your serializers that returns your relationship structs. You should be able to set the struct's value for the group or user relationship before returning it.

**Comment by pollingj** [comment]
Thanks @alanpeabody, I'd pretty much decided option 2 was roughly where I was going to go.

I've moved from the world of Rails where Lazy loading, has made me lazy, so data was just always available.  I was a little surprise the Preloading in Ecto only appeared to work one way, rather than both ways.

**Comment by alanpeabody** [comment]
Yeah, it is different, however I can't even tell you how many rails apps I have seen with "performance problems" that are really only improper use of lazy loading.

You can of course use `Ecto.Model.assoc/2` to load later, but know it is explicitly a potentially bad idea. I toyed with calling `Ecto.Model.assoc/2` automatically in serializers if a relationship was not loaded, but decided it was asking for performance trouble.

**Comment by pollingj** [comment]
Completely agree, whilst lazy loading can be useful, it does stop people thinking about the proper way of doing things.  I'm going to stick with Preloading and handle the count stuff I need differently.
