### ISSUE TITLE
How to override links to support pagination

### ISSUE THREAD

**Issue by vysakh0** [AgilionApps/ja_serializer#23]
```json
{
  "data": [
    {
      "type": "article",
      "id": "3",
      "attributes": {
        "title": "JSON API paints my bikeshed!",
        "body": "The shortest article. Ever.",
        "created": "2015-05-22T14:56:29.000Z",
        "updated": "2015-05-22T14:56:28.000Z"
      }
    }
  ],
  "links": {
    "self": "http://example.com/articles?page[number]=3&page[size]=1",
    "first": "http://example.com/articles?page[number]=1&page[size]=1",
    "prev": "http://example.com/articles?page[number]=2&page[size]=1",
    "next": "http://example.com/articles?page[number]=4&page[size]=1",
    "last": "http://example.com/articles?page[number]=13&page[size]=1"
  }
}
```

Currently I could only set the `self` location in `ja_serializer`.  Is there way to do this? It would be nice to have something that can be override like

```elixir
def links(model, conn) do
 %{
   "self" => ".."
 }
end
```

**Comment by alanpeabody** [comment]
This isn't currently supported :-/. I had been planning to use something in the options you can pass into `format/3`, but links in the serializer may be a better approach.

**Comment by alanpeabody** [comment]
@vysakh0, out of curiosity, are you using https://github.com/drewolson/scrivener for pagination or rolling your own?

**Comment by vysakh0** [comment]
Yeah, I'm using `scrivener` library. 

May be we should have something like Active Model Serializer's support for pagination library https://github.com/rails-api/active_model_serializers/blob/master/docs/howto/add_pagination_links.md .

**Comment by alanpeabody** [comment]
Yeah, I think we could probably accept a `Scrivener.Page` struct and parse the object into options.

So ideally we have 3 interfaces:

1) Just pass in a `Page`:

```elixir
MyApp.PostSerializer.format(Repo.paginate(query, page: 2, page_size: 5), conn, [])
```

2) Pass in page info in the opts directly:

```elixir
MyApp.PostSerializer.format(results, conn, [first: 1, last: 20, next: 2, prev: nil])
```

3) Customize/override links:

```elixir
def links(model, conn) do
  Dict.merge(super(model, conn), %{
    "foo" => "http://foo.bar"
  })
end
```

**Comment by vysakh0** [comment]
I've tried to implement this in the second suggested (sorta), have given a pull request, looking forward for your comments.

**Comment by alanpeabody** [comment]
Awesome, thanks! I will take a look tonight.

**Comment by ionull** [comment]
Is this added on v0.4.0?

**Comment by alanpeabody** [comment]
@ionull yup.

Please see: https://github.com/AgilionApps/ja_serializer#pagination

If you have any issues please let me know.

**Comment by ionull** [comment]
I tried with both model: page and model: page.entries, opts: %{page: page} but they didn’t work


—

**Comment by alanpeabody** [comment]
You are using Scrivener for pagination? Can you share more code either here or in a new issue as well as any errors or serialization results?

**Comment by ionull** [comment]
Ya, I'm using Scrivener for pagination. It returned such error: https://gist.github.com/ionull/61b3ea6ae6a241a320ae

**Comment by ionull** [comment]
sorry, figured out the problem, use rm -rf _build to clean cache helps
