### ISSUE TITLE
Default type doesn't properly translate camel case words

### ISSUE THREAD

**Issue by dmarkow** [AgilionApps/ja_serializer#27]
If I have a `MyApp.PostView` module, the `type` in the output is correctly extracted from the module name and set to `post`. However, if I have `MyApp.BookStoreView`, the `type` is set to `bookstore` instead of `book_store` as I would expect.

`Mix.Utils` includes an approach at an `underscore` method, though it's lengthy at 11 function clauses. We could also do a very basic approach and just use `String.replace` with a Regex, prefixing any capital letters with an underscore.

In the mean time, adding a `def type, do: "book_store"` works.

**Comment by alanpeabody** [comment]
Oh, good find. I think ideally this should go through the formatter that is defined by the user: https://github.com/AgilionApps/ja_serializer#attribute--relationship-key-format

**Comment by linstula** [comment]
@alanpeabody I think @dmarkow may be referring to the key value, rather than the key name. If I'm not mistaken, the formatter's primary responsibility seems to be formatting the key names, right?

It seems like the `"type"` value should follow the same format of the key names by default. So, if I specified
```exs
config :ja_serializer,
  key_format: :dasherized
```
in `config.exs` I would expect a view named MyApp.BookStoreView to return:
```exs
%{
  data: %{
    type: "book-store",
    id: "",
    attributes: %{}
  }
}
```
Rather than:
```exs
%{
  data: %{
    type: "bookstore",
    id: "",
    attributes: %{}
  }
}
```

**Comment by alanpeabody** [comment]
Yup, I agree.

**Comment by linstula** [comment]
@alanpeabody do you plan to cut a new release in the near future? Wondering if I should lock to the commit or hold out for the next release :)

**Comment by alanpeabody** [comment]
@linstula I can push out a new release tonight, going to look into the performance thing first: https://github.com/AgilionApps/ja_serializer/commit/52225abdef1315e393470a449d3962385a446d40

**Comment by linstula** [comment]
awesome, thanks!
