### ISSUE TITLE
Add to jsonapi.org

### ISSUE THREAD

**Issue by alanpeabody** [AgilionApps/ja_serializer#28]
Once includes and sparse field-sets are in place.

**Comment by green-arrow** [comment]
I'm not sure what the process is to get this added to the implementations page, but the two items remaining are now completed 😄

**Comment by alanpeabody** [comment]
Thanks for the reminder, PR opened:

https://github.com/json-api/json-api/pull/927

**Comment by alanpeabody** [comment]
merged. :+1:
