### ISSUE TITLE
Don't always embed related data?

### ISSUE THREAD

**Issue by bcardarella** [AgilionApps/ja_serializer#3]
Is there a way to force the serializer *not* to embed the relationhip's data? For example, I would like the following:

```json
{
    "jsonapi": {
        "version": "1.0"
    },
    "data": [
        {
            "type": "event",
                "relationships": {
                    "event-category": {
                        "data": {
                            "type": "event-category",
                            "id": "1"
                        }
                    },
                },
            },
            "id": "11",
            "attributes": { }
        }
    ]
}
```

Basically, the `included` object does not get into the final output. I supposed I could just delete the key from the result of the serializer, just checking to see if there is a way to declare this in the serializer itself.

**Comment by alanpeabody** [comment]
Yup, the data is only side-loaded/included if you use the `included` option when defining the relationship.

You want to define your relationship something like:

```elixir
serialize "event" do
  has_one :event-category, 
    type: "event-category", # populates type field
    field: :event_category_id # indicates what key in the struct is the foreign key.
end
```

Let me know if this works for you.

Upcoming releases will focus on more inference/better Ecto defaults. Also, the DSL may lean away from macros and towards behaviors.
