### ISSUE TITLE
has_one relationship formatted as an array instead of an object

### ISSUE THREAD

**Issue by andruby** [AgilionApps/ja_serializer#36]
According to JSONAPI.org (http://jsonapi.org/format/#document-resource-object-linkage) 
> Resource linkage MUST be represented as: 
> * a single resource identifier object for non-empty to-one relationships.
> * null for empty to-one relationships.

With ja_serializer 0.5.0, when declaring a has_one relationship, I either get an empty array `[]` (if the relationship is empty) or an array with one resource identifier object `[{type: "user", id: "1"}]`. It seems as if `has_one/2` does the same as `has_many/2`.

I'll dive into the code tomorrow, but wanted to know if I missed something.

**Comment by alanpeabody** [comment]
Thanks for the report. We tried to hit address this in https://github.com/AgilionApps/ja_serializer/pull/29 , but it might be worth another look and some more tests.

Currently there is very little difference between has_many and has_one at a code level. That may need to change.

**Comment by andruby** [comment]
@alanpeabody I'm sorry, this does actually work correctly when the association is a single object vs a collection. I was using the following code to fetch the user of a contact:

```elixir
  has_one :user, type: "user"

  def user(model, conn) do
    case model.user do
      %Ecto.Association.NotLoaded{} ->
        model
        |> Ecto.Model.assoc(:user)
        |> Repo.all # <- This caused the array behavior, should be Repo.one
        other -> other
    end
  end
```

Changing the Repo.all to Repo.one fixed the behavior.

**Comment by alanpeabody** [comment]
Okay, great!
