### ISSUE TITLE
content type negotiation

### ISSUE THREAD

**Issue by zipme** [AgilionApps/ja_serializer#37]
It seems now if I include ContentTypeNegotiation plug then the request must have content-type set to "application/vnd.api+json". However when I'm uploading a file along with a JSON document the content-type has to be "multipart/form-data". Any idea what would be the best way to solve this? Thanks!

**Comment by alanpeabody** [comment]
Oh, great question.

I don't know of anything in the spec about uploads. You may have to mount your upload point in a different pipeline w/o the ContentType negotiation plug.

An alternative might be to add some ability to skip that plug on certain routes. I have no idea what might look like.
