### ISSUE TITLE
Define a relationship without preloading?

### ISSUE THREAD

**Issue by ianwalter** [AgilionApps/ja_serializer#47]
I'm sorry if I missed this but how do you serialize a model with relationships without having to preload the related models? I have a couple `has_one`'s defined in the serializer but do not have `included` set to true. Still I get the following error:
```
Please pre-fetch the relationship before serialization or override the
     profile_image/2 function in your serializer.
```
I would like the JSON to have the relationships defined with their IDs so that the client knows about the relationships but not have to preload the related data (since the client already has that data). Not sure but this might be related to #45.

**Comment by alanpeabody** [comment]
@ianwalter, the field and type relationship keys are what you are looking for:

```elixir
has_one :author, field: :author_id, type: "user"
```

alternatively you can do:

```elixir
has_one :author, type: "user"

def author(model, _), do: model.author_id
```

The relationship DSL could probably use some better documentation, I will work on it.

**Comment by ianwalter** [comment]
Thanks @alanpeabody, I think the problem was that I forgot to add the `_id` to the name I specified in `field`.

**Comment by ianwalter** [comment]
Actually this didn't work with multiple associations. I get the same message. Here is an example of my code:
```elixir
# book_serializer.ex
has_one :user, serializer: UserSerializer, field: :user_id, type: "user"
has_one :author, serializer: AuthorSerializer, field: :author_id, type: "author"

# book_controller_test.ex
book = Ecto.build_assoc user, :books, book_attrs
book = Map.put book, :author_id, author.id
book = BookSerializer.format book
```

The code works fine with just the first association (user, even though its not loaded). Once I add the `author_id` it complains about the associations not being preloaded.

**Comment by alanpeabody** [comment]
Yup, you are absolutely right.

These two lines need to be switched: https://github.com/AgilionApps/ja_serializer/blob/master/lib/ja_serializer/builder/relationship.ex#L40-L41

I will add some test cases around this and push out a new release later today.

**Comment by alanpeabody** [comment]
Actually that isn't the issue, at least that won't raise an error.

Can you provide a stack trace indicating where the relationship is being accessed?

**Comment by ianwalter** [comment]
I'm sorry I decided to go a different route and can't reproduce. 
I'm going to close this for now since it was probably my error.
