### ISSUE TITLE
How to serialize datetime

### ISSUE THREAD

**Issue by sporto** [AgilionApps/ja_serializer#5]
Hi, I would like some help to figure out how to serialize datetime columns:

My Ecto models looks like:

```
	schema "matches" do
		...
		field :time, :datetime

		timestamps
	end
```

My serializer:

```
	serialize "matches" do
		...

		attributes [... :time, :inserted_at]

	end
```

Time is a `timestamp` column in PG

The error I get:

```
** (exit) an exception was raised:
    ** (Poison.EncodeError) unable to encode value: {{2015, 7, 31}, {8, 39, 43, 0}}
```

So the datetime column just comes out as nested tuples. At some point I want to convert that to iso8601.

Where would I do this? Somewhere in the serializer seems like the correct place. Thanks

**Comment by sporto** [comment]
On the same topic, when I add in my serializer

```
attributes [... :inserted_at]
```

I get:

```
			"inserted_at": {
				"year": 2015,
				"utc_off": 0,
				"usec": 0,
				"timezone": "Etc/UTC",
				"std_off": 0,
				"sec": 0,
				"month": 7,
				"min": 0,
				"hour": 0,
				"day": 1,
				"abbr": "UTC"
			},
```

I would expect to get ISO 8601. How can I change this?

**Comment by sporto** [comment]
I changed my Ecto model to:

```
	schema "matches" do
		...
		field :time, Ecto.DateTime

		timestamps
	end
```

Now I get:

```
"time": "2015-07-31T08:39:43Z",
```

:)

Still I would like to know about doing the same for `inserted_at`, thanks

**Comment by alanpeabody** [comment]
@sporto values are passed to your JSON library w/o modification, so w/ Poison that means you have total control of how different data structures are serialized by implementing the protocol.

I have added the following to my project. (I am not using Phoenix, I think some of this may already be baked in):

```elixir
defimpl Poison.Encoder, for: [Ecto.Date, Ecto.Time, Ecto.DateTime] do
  def encode(dt, _opts), do: <<?", @for.to_iso8601(dt)::binary, ?">>
end

defimpl Poison.Encoder, for: [Tuple] do
  # Assumption is anything in this tuple format is an Ecto.DateTime
  def encode({{_y, _m, _d}, {_h, _min, _s, _ms}} = dt, _opts) do
    {:ok, dt} = Ecto.DateTime.load(dt)
    <<?", Ecto.DateTime.to_iso8601(dt)::binary, ?">>
  end
end
```

In the next few releases Ecto and Phoenix support should be improving, so I may add this to the library itself.
