### ISSUE TITLE
Different attributes set

### ISSUE THREAD

**Issue by zipme** [AgilionApps/ja_serializer#51]
Is that possible to use different attributes in different situations?

For example, lets say I have a model which has these attrs: `[:name, :email, :address]`.  When I render the model in "index.json" I would like to only show [:name, :email] while in "show.json" I would like to show all attrs.

I am thinking maybe we can add another macro `attributes/2` in `Serializer` which we can then do 
```elixir
defmodule MyApp.ArticleSerializer do
  use JaSerializer

  location "/articles/:id"

  attributes [:title, :tags, :body, :excerpt]
  attributes :foo, [:body, :excerpt]
  attributes :bar, [:title, :tags]
end
```
and then 

```elixir
model
|> MyApp.ArticleSerializer.format(conn, [attributes: :foo])
|> Poison.encode!
```

Thanks!

**Comment by alanpeabody** [comment]
You can leverage the JSON-API spec sparse fieldsets as described here: https://github.com/AgilionApps/ja_serializer#fields

Alternatively you can override the `attributes/2` behaviour callback and not use the DSL at all.

```elixir
def attributes(model, conn) do
  case conn.private.phoenix_view do
    :index -> Map.take(model, ~w(name email)i)
    :show -> Map.take(model, ~w(name email address)i)
  end
end
```

**Comment by alanpeabody** [comment]
Let me know if either of those don't work for you!

**Comment by zipme** [comment]
🆒 Sparse fieldsets it is! Thanks very much!
