### ISSUE TITLE
using with MyApp.ErrorView

### ISSUE THREAD

**Issue by xcambar** [AgilionApps/ja_serializer#52]
Hi and thanks for bringing JSON-API to the Elixir ecosystem!

I would like to replace the `MyApp.ErrorView` generated by Phoenix with a JSON-API compatible payload.

I thought that would be fairly easy, but I can't get it to work.

Here's the setup:

* phoenix 1.1.1, with the endpoint configured with `debug_errors: false`
* JaSerializer 0.6.1

Here's the actual ErrorView:

```elixir
defmodule PhoenixTodosApi.ErrorView do

  def render("500.json-api", assigns) do
    require IEx; IEx.pry
    #What to do here?
  end
end
```

As expected, the code halts in `render/2`, but I can't figure out what to do with JaSerializer, despite many attempts. Can you provide some guidance, please?

**Comment by alanpeabody** [comment]
You can use https://github.com/AgilionApps/ja_serializer/blob/master/lib/ja_serializer/error_serializer.ex if you would like, but the spec is pretty basic for a standard error, so you could render manually too.

```elixir
  def render("500.json-api", assigns) do
    render_api_error(%{
      status: "500",
      title: "Something has gone horribly wrong. Please call for help, our address is ...."
    })
  end

  defp render_api_error(error) do
    error
    |> JaSerializer.ErrorSerializer.format
    |> Poison.encode
  end
```

If you are just want to render validation errors in your controller you can:

```elixir
    conn
      |> put_status(422)
      |> render(:errors, data: changeset)
```
