### ISSUE TITLE
key_format config not working

### ISSUE THREAD

**Issue by icn** [AgilionApps/ja_serializer#63]
I have put the following lines to config.exs of phoenix framework 

config :ja_serializer,
  key_format: :underscored

But I still got dash-erized json response like this

{"jsonapi":{"version":"1.0"},"data":{"type":"maxbid","links":{"self":"/invocies/115236"},"id":"115236","attributes":{"user-id":2, "invoice-id": 115236}}}

 I would like to get 

{"jsonapi":{"version":"1.0"},"data":{"type":"maxbid","links":{"self":"/invocies/115236"},"id":"115236","attributes":{"user_id":2, "invoice_id": 115236}}}

This is  api pipeline

 pipeline :api do
    plug :accepts, ["json"]
    plug JaSerializer.Deserializer
  end 

What else I need to do to get underscored  json response ?

**Comment by alanpeabody** [comment]
Thanks for your report @icn, I will look into it. Can you let me know if you run `mix deps.clean ja_serializer && mix deps.get` if the problem is resolved?

**Comment by icn** [comment]
@alanpeabody  the issue is gone : ) after running `mix deps.clean ja_serializer && mix deps.get`

**Comment by alanpeabody** [comment]
Great, that makes sense, I am storing the value in a module attribute at compile time. I will re-think if that is the best way.
