### ISSUE TITLE
Format query params

### ISSUE THREAD

**Issue by linstula** [AgilionApps/ja_serializer#64]
Currently, pagination links produce a link with underscored query params Eg:
`"/api/v1/posts?page[page]=1&page[page_size]=20"`

I wanted to get your thoughts on how you feel about formatting query params to be consistent with `key_format` specified in config.exs so that if you specified:

```exs
config :ja_serializer,
  key_format: :dasherized
```

the resulting link would be: `"/api/v1/posts?page[page]=1&page[page-size]=20"`.
Thoughts?

**Comment by alanpeabody** [comment]
Good question, I hadn't noticed the discrepancy.

I think we could format them as long as we reverse the formatting on the way back in so `params["page"]` can be used with out manual manipulation.
