### ISSUE TITLE
Deserializing error

### ISSUE THREAD

**Issue by zipme** [AgilionApps/ja_serializer#69]
In the latest release (0.7.0), when the request body contains `%Ecto.Date{}` or `%Plug.Upload{}`, an error occurred: 

```elixir
  data = %{
     attributes: %{
       attachment: %Plug.Upload{path: "image.png", filename: "image.png"}
    }
  }

  conn |> put(post_path(conn, :update, post), data: data)
```

```elixir
** (Protocol.UndefinedError) protocol Enumerable not implemented for %Plug.Upload{...}
```

The code above runs on okay with version 0.6.2.

**Comment by alanpeabody** [comment]
Thanks, I will get a test and fix up asap

**Comment by alanpeabody** [comment]
@zipme just looking into this. How would an Ecto.Date make it in via params?

**Comment by zipme** [comment]
@alanpeabody thanks for looking into it! I think I was doing something wrong here, instead of passing Ecto.Date struct in the params in my test I should be using date string.
