### ISSUE TITLE
Move away from :model based parameter

### ISSUE THREAD

**Issue by josevalim** [AgilionApps/ja_serializer#73]
Hi folks!

Phoenix v1.2 and Ecto v2.0 are becoming more explicit on what they call model. Previously, model was used to refer to both the module AND the data structure. In future versions, model will always refer to the module, as it does in controllers and views. This means API like this:

    render conn, model: PhoenixExample.Repo.get(PhoenixExample.Article, params[:id])

should probably be rewritten as:

    render conn, struct: PhoenixExample.Repo.get(PhoenixExample.Article, params[:id])

You don't need to use struct, of course, the point is that model would be semantically wrong.

Anyway, this is just a heads up I thought worth giving after taking a look at the README :heart:

**Comment by alanpeabody** [comment]
Thanks @josevalim I have been wanting to standardize this (currently accepts `:data`, `:model` and an atom of the struct name), so thanks for the nudge!
