### ISSUE TITLE
allow Phoenix to handle its own encoding

### ISSUE THREAD

**Issue by bcardarella** [AgilionApps/ja_serializer#77]
The current JaSerializer.View will force its own encoding on the rendered body: https://github.com/AgilionApps/ja_serializer/blob/master/lib/ja_serializer/phoenix_view.ex#L90

Instead ja_serializer should rely on Phoenix's own format_encoders to handle the proper encoding.

Currently if `json-api` is registered as a type for encoding in the config:

```elixir
config :phoenix, :format_encoders,
  "json-api": Poison
```

the result is that `json-api` responses are now double encoded. I believe if you instruct people to add the encoder to their config you can remove the forced encoding on the body for `render/2`s

**Comment by alanpeabody** [comment]
Oh great, I didn't know about that. I will get it in the next release. Thanks Brian.
