### ISSUE TITLE
How to selectively show attributes for different users  [question]

### ISSUE THREAD

**Issue by vysakh0** [AgilionApps/ja_serializer#79]
In my phoenix app, I have a `BookingView` with

```
attributes [:commission, :admin_commission]
```

Only if the user is `admin`, one should get all attributes. If the role is any other, one shouldn't be able to see few attributes. 

In the normal phoenix view, I think I could do this 

```elixir
def render("show.json", %{data: data, role: :admin}) do
  Map.take(data, [:admin_commission, :commission])
end
def render("show.json", %{data: data}) do
  Map.take(data, [:commission])
end
```

And in controller

```elixir
def show(conn, %{ "id" => id }) do
   booking = Repo.get!(Booking, id)
   render(conn, "show.json", [data: booking, role: conn.assigns[:user].role])
end
```

I was wondering how to handle this scenario when using JaSerializer

**Comment by alanpeabody** [comment]
Currently the best way to handle this is with the `attributes/2` callback https://hexdocs.pm/ja_serializer/JaSerializer.Serializer.html#c:attributes/2. (Not to be confused with the `attributes/1` macro.)

You example could be written in one of two ways:

1) Still leveraging the attributes/1 macro (and associated function definitions):

```elixir

defmodule BookingView do
  use JaSerializer.PhoenixView
  attributes [:commission, :admin_commission]

  def attributes(booking, conn) do
    attrs = super(booking, conn)
    case conn.assigns[:current_user].role do
      :admin -> attrs
      _ -> Map.take(attrs, [:commission])
  end
end
```

**Comment by vysakh0** [comment]
@alanpeabody Thank you very much :+1:  :+1: Also, today I learnt about `super` and `defoverridable`
