### ISSUE TITLE
key :data not found in...

### ISSUE THREAD

**Issue by hunterboerner** [AgilionApps/ja_serializer#84]
```
** (exit) an exception was raised:
    ** (KeyError) key :data not found in: %{conn: %Plug.Conn{adapter: {Plug.Adapters.Cowboy.Conn, :...}, assigns: %{data:...}
        lib/ja_serializer/builder/resource_object.ex:20: JaSerializer.Builder.ResourceObject.build/1
        lib/ja_serializer/builder/top_level.ex:23: JaSerializer.Builder.TopLevel.build/1
```

Controller code:
```elixir
render(conn, data: Repo.all(Project))
```

`render(...)` put the  `:data` key under `:assigns`. This was working on 8b7c5346b75a404e45c02c9b9a2e80b94788530b but not on the latest commit, beb59f01c5d2939ceb493b105bc3273ca5d2e282 .

**Comment by alanpeabody** [comment]
Thanks, I will look into it.

**Comment by alanpeabody** [comment]
@hunterboerner I am a bit stumped on this. If you pass in the action name does it make a difference?

**Comment by hunterboerner** [comment]
Uh... somehow it's working now. Either this was fixed in one of the PRs you just merged or my build directory needed to be cleaned (though it started working before I did that).

https://github.com/rabbit-ci/rabbit-ci/commit/6993d2171ae6c3d551eef2a5da71b22d04fa60b1

**Comment by alanpeabody** [comment]
:+1:
