### ISSUE TITLE
Relationships are not dasherize

### ISSUE THREAD

**Issue by zion03** [AgilionApps/ja_serializer#85]
From documenation `By default keys are dash-erized as per the jsonapi.org recommendation, but keys can be customized via config.` My relationship keys are not dasherize or i'm doing something wrong?

I trying serialize model with:

        has_one :userOne,
        has_one :userTwo,

And relationships looks like 

          "relationships":{
            "userTwo":{
               "data":{
                  "type":"user",
                  "id":"35"
               }
            },
            "userOne":{
               "data":{
                  "type":"user",
                  "id":"37"
               }
            }
         }

**Comment by alanpeabody** [comment]
@zion03 the library expects that your relationships would be `snake_cased` as per elixir standard practices for functions and variables.

If you change to:

```elixir
    has_one :user_one
    has_one :user_two
```

If you run into any more issues please feel free to re-open this issue.
