### ISSUE TITLE
Add meta to attribute callback

### ISSUE THREAD

**Issue by zion03** [AgilionApps/ja_serializer#93]
Is it possible to add meta or other additional (outer scope) data to attribute callback. It's not a widely used case, but I am interesting in right way to do it. 

For example:

```
_data = %{time: 123}

struct
|> MyApp.ArticleSerializer.format(conn, [meta:  _data])
```

```
attributes [:title]

def title(model, _conn) do
    # what is the best way to access _data 
   if model.time < _data.time do ...
  
end
```
Add it to _conn looks like not clear.

Thanks for answer and awesome lib

**Comment by alanpeabody** [comment]
Thanks for the question, this is actually not a use case I have thought about.

Is this actually meta data (which is serialized into response)? Or are you just looking to pass some info from the outside the serializer into it?

**Comment by zion03** [comment]
This is some info data (external, not contain in model) not needed in meta actually  but will change the json output. Similar to  `if conn.assigns[:current_user].is_admin do` form documentation.

**Comment by alanpeabody** [comment]
At this point I would probably recommend just assigning it to the conn. If there is enough demand I would be interested in a more comprehensive way to pass in additional data, but the conn.assigns is a workable solution for now.
