### ISSUE TITLE
Many-to-many association

### ISSUE THREAD

**Issue by kaermorchen** [AgilionApps/ja_serializer#99]
Hello.

Ecto 2 has [many-to-many](https://hexdocs.pm/ecto/2.0.0-rc.3/Ecto.Schema.html#many_to_many/3) association. Do ja_serializer support this type association?

**Comment by alanpeabody** [comment]
@kaermorchen I believe it should, from the serializer's perspective it is just a has_many relationship.

One thing I would be careful with is recursively including on both sides of the relationship. While JaSerializer should not get into a loop it could possibly end up loading and serializing a lot of data or at least hitting a relationship not loaded exception.

I am going to close this, but if you have any other questions or run into any problems please re-open it!

**Comment by tmthn** [comment]
Right now i have the above described loop problem, but only when a custom serializer is defined. When I use the field, include and type params without a serializer, js_serializer returns nothing. Is there a way to avoid this behaviour?

**Comment by alanpeabody** [comment]
@tmthn Can you provide a few more details? Ecto relationships, ja_serializer relationship definitions, what you have preloaded, and what you expect would be great, thanks!

**Comment by tmthn** [comment]
Sure, here is my view:

```
defmodule Mq2.DataGridEntityView do
  use Mq2.Web, :view
  use JaSerializer.PhoenixView

  attributes [:name, :url, :inserted_at, :updated_at]
  
  has_many :data_grid_columns,
    serializer: Mq2.DataGridColumnView,
    include: true

end
```

controller methods:
```
def index(conn, params) do
    data_grid_entities = params
      |> data_grid_entity_query
      |> Repo.all

    render(conn, "index.json-api", data: data_grid_entities)
  end

defp data_grid_entity_query(%{"filter" => %{"name" => name}}) do
    from dg in DataGridEntity,
      where: dg.name == ^name,
      preload: [:data_grid_columns]
end
```

and my schema:
```
schema "data_grid_entities" do
    field :name, :string
    field :url, :string
    many_to_many :data_grid_columns, Mq2.DataGridColumn, join_through: "data_grid_entities_columns"

    timestamps()
end
```

Thanks for your quick reply!

**Comment by alanpeabody** [comment]
That is just a warning, not an error, and frankly one I am surprised to see, what version are you using?

**Comment by tmthn** [comment]
I'm on version 0.10.1.

**Comment by alanpeabody** [comment]
And is the warning triggered in a controller test? Or where do you see it? Can you also post your DataGridColumnView?

**Comment by tmthn** [comment]
I updated my version to the current stable just in case to avoid any further conflicts. I don't have any tests for this controller right now. I tested the method by calling it with a model via ember-data. Here is the DataGridColumnView:

```
defmodule Mq2.DataGridColumnView do
  use Mq2.Web, :view
  use JaSerializer.PhoenixView

  attributes [:name, :format, :inserted_at, :updated_at]
  
  has_one :account,
    field: :account_id,
    type: "account"

end
```

**Comment by alanpeabody** [comment]
I don't see any problems TBH. If you IO.inspect data_grid_entities do you see the data you expect?

**Comment by tmthn** [comment]
Yes, here is the output:

```
[%Mq2.DataGridEntity{__meta__: #Ecto.Schema.Metadata<:loaded, "data_grid_entities">,
  data_grid_columns: [%Mq2.DataGridColumn{__meta__: #Ecto.Schema.Metadata<:loaded, "data_grid_columns">,
    account: #Ecto.Association.NotLoaded<association :account is not loaded>,
    account_id: nil, format: "string", id: 2,
    inserted_at: #Ecto.DateTime<2016-09-26 16:56:30>, name: "firstName",
    updated_at: #Ecto.DateTime<2016-09-26 16:56:30>},
   %Mq2.DataGridColumn{__meta__: #Ecto.Schema.Metadata<:loaded, "data_grid_columns">,
    account: #Ecto.Association.NotLoaded<association :account is not loaded>,
    account_id: nil, format: "string", id: 3,
    inserted_at: #Ecto.DateTime<2016-09-26 16:56:30>, name: "lastName",
    updated_at: #Ecto.DateTime<2016-09-26 16:56:30>},
   %Mq2.DataGridColumn{__meta__: #Ecto.Schema.Metadata<:loaded, "data_grid_columns">,
    account: #Ecto.Association.NotLoaded<association :account is not loaded>,
    account_id: nil, format: "string", id: 4,
    inserted_at: #Ecto.DateTime<2016-09-26 16:56:30>, name: "street",
    updated_at: #Ecto.DateTime<2016-09-26 16:56:30>},
   %Mq2.DataGridColumn{__meta__: #Ecto.Schema.Metadata<:loaded, "data_grid_columns">,
    account: #Ecto.Association.NotLoaded<association :account is not loaded>,
    account_id: nil, format: "zip", id: 5,
    inserted_at: #Ecto.DateTime<2016-09-26 16:56:30>, name: "zip",
    updated_at: #Ecto.DateTime<2016-09-26 16:56:30>}], id: 1,
  inserted_at: #Ecto.DateTime<2016-09-01 18:31:13>, name: "lead",
  updated_at: #Ecto.DateTime<2016-09-01 18:31:13>, url: "leads"}]
```

**Comment by alanpeabody** [comment]
Yeah, everything looks good to me, but nothing at all is being returned? what is the response code?

**Comment by tmthn** [comment]
There is no response code at all. It is stuck at "pending" and ja_serializer returns this already mentioned warning "warning: Elixir.Mq2.DataGridColumnView.format/3 is deprecat …" in a loop.

**Comment by tmthn** [comment]
I found the problem. My model was using a column called "format" and somehow ja_serializer thought I was calling the "Elixir.Mq2.DataGridColumnView.format/3" method.

**Comment by alanpeabody** [comment]
Oh man, I totally didn't catch that, sorry!

FWIW, that error will go away when the deprecated method is removed. In the mean time if you use `attributes/2` callback instead of the `attributes/1` macro you can still use format as an attribute.

Opened an issue to track this: https://github.com/AgilionApps/ja_serializer/issues/175
